GET http://localhost:3000/api/genres/3
###
GET http://localhost:3000/api/genres 
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzExYmRjNTM5Y2Q1NjEzZDAxOTk1ZjQiLCJpYXQiOjE1NDQ2NjY1NzN9.FtQOr6yxYAGpcSOa1m_2ww1ncAS3brR9tjyYZxfHG-I
###
POST http://localhost:3000/api/genres
content-type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzExYmRjNTM5Y2Q1NjEzZDAxOTk1ZjQiLCJpYXQiOjE1NDQ2NjY1NzN9.FtQOr6yxYAGpcSOa1m_2ww1ncAS3brR9tjyYZxfHG-I

{
    "name": "Sci-fi"
}
###
POST http://localhost:3000/api/genres
content-type: application/json

{
    "name": "Comedy"
}
###
POST http://localhost:3000/api/genres
content-type: application/json

{
    "name": "Drama"
}
###
PUT http://localhost:3000/api/genres/6
content-type: application/json

{
    "name": "updated genre"
}
###
DELETE http://localhost:3000/api/genres/5bfcad630c0ff721ecfdc83f
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YmZjYWNlMTBjMGZmNzIxZWNmZGM4M2UiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE1NDMyODczNjJ9.C9F_khD0mSU_4gFbgSLiBrZz244QZtgy4Kxxw9TJ_b8